version:  "3.7"

x-vars:
  - &LOCALE ${LOCALE:-ru}
  - &DOCUMENT_DB ${DOCUMENT_DB:-true}

secrets:
  DB:
    external: true
  TELEGRAM_TOKEN:
    external: true

services:
  ru-bot:
    image: 977007773325.dkr.ecr.us-east-1.amazonaws.com/minq-bot:1.2.0 
    secrets:
      - DB
      - TELEGRAM_TOKEN
    environment: 
      LOCALE: *LOCALE
    volumes:
      - /tmp:/tmp
