version:  "3.7"

x-vars:
  - &LOCALE_RU ${LOCALE:-ru}
  - &LOCALE_EN ${LOCALE:-en}
  - &TELEGRAM_TOKEN_RU: ${TELEGRAM_TOKEN_RU:-xxxxxx:xxxxxx}
  - &TELEGRAM_TOKEN_EN: ${TELEGRAM_TOKEN_EN:-xxxxxx:xxxxxx}

services:
  ru-bot:
    image: 977007773325.dkr.ecr.us-east-1.amazonaws.com/minq-bot:1.2.4 
    environment: 
      LOCALE: *LOCALE_RU
      TELEGRAM_TOKEN: *TELEGRAM_TOKEN_RU
      DB: mongodb://mongodb:27017/minq
  en-bot:
    image: 977007773325.dkr.ecr.us-east-1.amazonaws.com/minq-bot:1.2.4 
    environment: 
      LOCALE: *LOCALE_EN
      TELEGRAM_TOKEN: *TELEGRAM_TOKEN_EN
      DB: mongodb://mongodb:27017/minq
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
      - ./tmp:/tmp
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet