version:  "3.7"

x-vars:
  - &LOCALE_RU ${LOCALE:-ru}
  - &LOCALE_EN ${LOCALE:-en}

secrets:
  TELEGRAM_TOKEN_RU:
    external: true
  TELEGRAM_TOKEN_EN:
    external: true

services:
  ru-bot:
    image: 977007773325.dkr.ecr.us-east-1.amazonaws.com/minq-bot:1.2.4 
    secrets:
      - TELEGRAM_TOKEN_RU
    environment: 
      LOCALE: *LOCALE_RU
      DB: mongodb://mongodb:27017/minq
  en-bot:
    image: 977007773325.dkr.ecr.us-east-1.amazonaws.com/minq-bot:1.2.4 
    secrets:
      - TELEGRAM_TOKEN_EN
    environment: 
      LOCALE: *LOCALE_EN
      DB: mongodb://mongodb:27017/minq
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet